### ISSUE TITLE
[server] Upgrade to Mongo 6

### ISSUE THREAD

**Issue by kaaloo** [refugies-info/karfur#2150]
- Mongo 5 reaches EOL on October 31, 2024

Documentation: https://www.mongodb.com/docs/atlas/tutorial/major-version-change/

**Comment by matthieu-fesselier** [comment]
We already use Mongo 7 on staging, and it seems to work fine. We could do the upgrade on production after doing some backups

**Comment by kaaloo** [comment]
That's great to know, thanks for that @matthieu-fesselier

**Comment by kaaloo** [comment]
Closing in favor of internal ticket on Monday
